import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import api from '../utils/api'

export default function AppsPage() {
  const navigate = useNavigate()
  const [apps, setApps] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [deleting, setDeleting] = useState(null)
  const [pushingGit, setPushingGit] = useState(null)

  const fetchApps = async () => {
    try {
      const data = await api.get('/apps')
      setApps(data.apps || [])
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchApps() }, [])

  // Poll for any generating apps
  useEffect(() => {
    const generating = apps.filter(a => a.status === 'generating')
    if (generating.length === 0) return
    const iv = setInterval(async () => {
      try {
        const data = await api.get('/apps')
        const updated = data.apps || []
        setApps(updated)
        if (!updated.some(a => a.status === 'generating')) clearInterval(iv)
      } catch {}
    }, 4000)
    return () => clearInterval(iv)
  }, [apps])

  const handleDelete = async (e, appId) => {
    e.stopPropagation()
    if (!confirm('Delete this app? This cannot be undone.')) return
    setDeleting(appId)
    try {
      await api.delete(`/apps/${appId}`)
      setApps(prev => prev.filter(a => a.id !== appId))
    } catch (err) {
      alert('Failed to delete: ' + err.message)
    } finally {
      setDeleting(null)
    }
  }

  const handleGithubPush = async (e, appId) => {
    e.stopPropagation()
    setPushingGit(appId)
    try {
      const data = await api.post(`/apps/${appId}/github-push`)
      setApps(prev => prev.map(a => a.id === appId ? { ...a, github_repo_url: data.url } : a))
      window.open(data.url, '_blank')
    } catch (err) {
      alert('GitHub push failed: ' + err.message)
    } finally {
      setPushingGit(null)
    }
  }

  const statusPill = s =>
    s === 'ready'      ? { bg: 'rgba(34,197,94,0.1)',  color: '#15803d', label: '✅ Ready' } :
    s === 'generating' ? { bg: 'rgba(245,158,11,0.1)', color: '#92400e', label: '⏳ Generating…' } :
                          { bg: 'rgba(239,68,68,0.1)',  color: '#dc2626', label: '❌ Failed' }

  if (loading) // 🚧 App generation is not live yet — show Coming Soon only
return (
  <div style={{minHeight:'70vh',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:14,fontFamily:"'Nunito',sans-serif",textAlign:'center',padding:'40px 20px'}}>
    <style>{CSS}</style>
    <div style={{fontSize:52}}>🚧</div>
    <h2 style={{fontFamily:"'Playfair Display',serif",fontSize:26,fontWeight:900,color:'#0a0a12'}}>
      App Generation — Coming Soon
    </h2>
    <p style={{color:'#72727f',fontWeight:500,fontSize:14,maxWidth:380,lineHeight:1.6}}>
      Full-stack app generation is still in development. You'll be able to build, preview, download, and host apps here soon.
    </p>
    <button className="aps-new-btn" onClick={() => navigate('/home')}>← Back to Home</button>
  </div>
)

  return (
    <>
      <style>{CSS}</style>
      <div className="aps-root">

        {/* Header */}
        <div className="aps-header">
          <div>
            <h1 className="aps-title">My Apps</h1>
            <p className="aps-sub">Full-stack apps generated by Claude AI</p>
          </div>
          <button className="aps-new-btn" onClick={() => navigate('/')}>
            + New App
          </button>
        </div>

        {error && (
          <div className="aps-error">
            <span>⚠️ {error}</span>
            <button className="aps-err-x" onClick={() => setError('')}>✕</button>
          </div>
        )}

        {/* Empty state */}
        {!loading && apps.length === 0 && !error && (
          <div className="aps-empty">
            <div style={{ fontSize: 46 }}>⚛️</div>
            <h3>No apps yet</h3>
            <p>Generate your first full-stack app — React frontend, Node.js backend, MySQL schema &amp; setup guide.</p>
            <button className="aps-new-btn" onClick={() => navigate('/')}>
              Build Your First App ⚡
            </button>
          </div>
        )}

        {/* Apps grid */}
        {apps.length > 0 && (
          <div className="aps-grid">
            {apps.map(app => {
              const sp = statusPill(app.status)
              return (
                <div
                  key={app.id}
                  className="aps-card"
                  onClick={() => app.id && navigate(`/app/${app.id}`)}
                >
                  <div className="aps-card-top">
                    <span className="aps-status-pill" style={{ background: sp.bg, color: sp.color }}>
                      {sp.label}
                    </span>
                    <span className="aps-date">
                      {new Date(app.created_at).toLocaleDateString('en-IN', {
                        day: 'numeric', month: 'short', year: 'numeric'
                      })}
                    </span>
                  </div>

                  <h3 className="aps-card-title">{app.title}</h3>
                  <p className="aps-card-prompt">&ldquo;{app.prompt}&rdquo;</p>

                  {app.download_paid && (
                    <span className="aps-free-badge">💳 Paid</span>
                  )}

                  <div className="aps-card-actions">
                    <button
                      className="aps-btn aps-btn-primary"
                      onClick={e => { e.stopPropagation(); app.id && navigate(`/app/${app.id}`) }}
                    >
                      Open →
                    </button>

                    {app.status === 'ready' && (
                      app.github_repo_url ? (
                        <button
                          className="aps-btn aps-btn-outline"
                          onClick={e => { e.stopPropagation(); window.open(app.github_repo_url, '_blank') }}
                        >
                          GitHub ↗
                        </button>
                      ) : (
                        <button
                          className="aps-btn aps-btn-outline"
                          onClick={e => handleGithubPush(e, app.id)}
                          disabled={pushingGit === app.id}
                        >
                          {pushingGit === app.id ? 'Pushing…' : 'Push to GitHub'}
                        </button>
                      )
                    )}

                    <button
                      className="aps-btn aps-btn-danger"
                      onClick={e => handleDelete(e, app.id)}
                      disabled={deleting === app.id}
                    >
                      {deleting === app.id ? '…' : '🗑️ Delete'}
                    </button>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>
    </>
  )
}

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800;900&family=Nunito:wght@400;500;600;700;800&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
@keyframes spin{to{transform:rotate(360deg)}}
@keyframes fadeUp{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}
@keyframes fadeIn{from{opacity:0}to{opacity:1}}

.aps-root{font-family:'Nunito',sans-serif;max-width:1100px;margin:0 auto;padding:40px 24px 80px;color:#0a0a12;}

/* HEADER */
.aps-header{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:32px;gap:16px;flex-wrap:wrap;}
.aps-title{font-family:'Playfair Display',serif;font-size:32px;font-weight:900;color:#0a0a12;letter-spacing:-1px;margin-bottom:4px;}
.aps-sub{font-size:14px;color:#72727f;font-weight:500;}
.aps-new-btn{background:#c0392b;color:#fff;border:none;padding:11px 22px;border-radius:10px;font-size:13px;font-weight:800;cursor:pointer;font-family:'Nunito',sans-serif;box-shadow:0 2px 10px rgba(192,57,43,0.3);transition:all .18s;white-space:nowrap;}
.aps-new-btn:hover{opacity:0.88;transform:translateY(-1px);}

/* ERROR */
.aps-error{background:rgba(239,68,68,0.06);border:1.5px solid rgba(239,68,68,0.2);border-radius:10px;padding:12px 16px;font-size:13px;color:#dc2626;font-weight:600;display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;}
.aps-err-x{background:none;border:none;color:#dc2626;font-size:16px;font-weight:800;cursor:pointer;padding:0;}

/* LOADING */
.aps-loading{display:flex;flex-direction:column;align-items:center;gap:14px;padding:100px 0;color:#a0a0b0;font-weight:600;font-family:'Nunito',sans-serif;}
.aps-spinner{width:36px;height:36px;border:3px solid #e2e2ea;border-top-color:#c0392b;border-radius:50%;animation:spin 1s linear infinite;}

/* EMPTY */
.aps-empty{text-align:center;padding:80px 20px;display:flex;flex-direction:column;align-items:center;gap:14px;animation:fadeUp .4s ease;}
.aps-empty h3{font-family:'Playfair Display',serif;font-size:22px;font-weight:800;color:#0a0a12;}
.aps-empty p{font-size:14px;color:#72727f;font-weight:500;max-width:380px;line-height:1.6;}

/* GRID */
.aps-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px;}

/* CARD */
.aps-card{background:#fff;border:1.5px solid #e2e2ea;border-radius:18px;padding:20px;display:flex;flex-direction:column;gap:12px;cursor:pointer;transition:all .2s;animation:fadeUp 0.3s ease;}
.aps-card:hover{border-color:#c0392b;box-shadow:0 8px 32px rgba(0,0,0,0.08);transform:translateY(-2px);}
.aps-card-top{display:flex;align-items:center;justify-content:space-between;gap:8px;}
.aps-status-pill{font-size:11px;font-weight:700;padding:4px 10px;border-radius:100px;white-space:nowrap;}
.aps-date{font-size:11px;color:#a0a0b0;font-weight:600;}
.aps-card-title{font-family:'Playfair Display',serif;font-size:17px;font-weight:800;color:#0a0a12;line-height:1.3;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;}
.aps-card-prompt{font-size:12px;color:#72727f;font-weight:500;line-height:1.55;font-style:italic;background:#fafafa;border:1px solid #f0f0f6;border-radius:8px;padding:9px 11px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;}

.aps-free-badge{font-size:11px;font-weight:700;color:#15803d;background:rgba(34,197,94,0.1);padding:4px 10px;border-radius:100px;align-self:flex-start;}

/* ACTIONS */
.aps-card-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:4px;}
.aps-btn{flex:1;min-width:88px;padding:8px 12px;border-radius:9px;font-size:12px;font-weight:700;cursor:pointer;font-family:'Nunito',sans-serif;border:none;transition:all .18s;display:flex;align-items:center;justify-content:center;gap:5px;white-space:nowrap;}
.aps-btn:disabled{opacity:0.45;cursor:not-allowed;transform:none !important;}
.aps-btn-primary{background:#0a0a12;color:#fff;}
.aps-btn-primary:hover:not(:disabled){background:#c0392b;}
.aps-btn-outline{background:#fff;color:#0a0a12;border:1.5px solid #e2e2ea;}
.aps-btn-outline:hover:not(:disabled){border-color:#0a0a12;background:#fafafa;}
.aps-btn-danger{background:#fff;color:#dc2626;border:1.5px solid rgba(220,38,38,0.2);flex:0 0 auto;min-width:auto;}
.aps-btn-danger:hover:not(:disabled){background:rgba(220,38,38,0.06);border-color:#dc2626;}

@media(max-width:600px){
  .aps-root{padding:28px 16px 64px;}
  .aps-title{font-size:24px;}
  .aps-grid{grid-template-columns:1fr 1fr;gap:12px;}
  .aps-card{padding:14px;gap:9px;border-radius:14px;}
  .aps-card-title{font-size:14px;}
  .aps-card-prompt{font-size:11px;padding:7px 9px;}
  .aps-status-pill{font-size:9px;padding:3px 7px;}
  .aps-date{font-size:9px;}
  .aps-card-actions{gap:6px;}
  .aps-btn{font-size:10px;padding:7px 8px;min-width:70px;}
}

@media(max-width:400px){
  .aps-grid{grid-template-columns:1fr;}
}
`