import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import api from '../utils/api'

export default function AppsPage() {
  const navigate = useNavigate()
  const [apps, setApps] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [deleting, setDeleting] = useState(null)

  const fetchApps = async () => {
    try {
      const data = await api.get('/apps')
      setApps(data.apps || [])
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchApps() }, [])

  // Poll for any generating apps
  useEffect(() => {
    const generating = apps.filter(a => a.status === 'generating')
    if (generating.length === 0) return
    const iv = setInterval(async () => {
      try {
        const data = await api.get('/apps')
        const updated = data.apps || []
        setApps(updated)
        if (!updated.some(a => a.status === 'generating')) clearInterval(iv)
      } catch {}
    }, 4000)
    return () => clearInterval(iv)
  }, [apps])

  const handleDelete = async (e, appId) => {
    e.stopPropagation()
    if (!confirm('Delete this app? This cannot be undone.')) return
    setDeleting(appId)
    try {
      await api.delete(`/apps/${appId}`)
      setApps(prev => prev.filter(a => a.id !== appId))
    } catch (err) {
      alert('Failed to delete: ' + err.message)
    } finally {
      setDeleting(null)
    }
  }

  const statusColor = s =>
    s === 'ready'      ? { bg: 'rgba(34,197,94,0.12)',  color: '#22c55e',  border: 'rgba(34,197,94,0.3)'  } :
    s === 'generating' ? { bg: 'rgba(245,158,11,0.12)', color: '#f59e0b',  border: 'rgba(245,158,11,0.3)' } :
                         { bg: 'rgba(239,68,68,0.12)',  color: '#ef4444',  border: 'rgba(239,68,68,0.3)'  }

  const statusLabel = s =>
    s === 'ready' ? '✅ Ready' : s === 'generating' ? '⏳ Generating...' : '❌ Failed'

  if (loading) return (
    <div style={S.center}>
      <div style={S.spinner} />
      <p style={{ color: '#a0a0b0', fontWeight: 600, fontSize: 14 }}>Loading your apps...</p>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  )

  return (
    <>
      <style>{CSS}</style>
      <div className="aps-root">
        <div className="aps-inner">

          {/* Header */}
          <div className="aps-header">
            <div>
              <h1 className="aps-title">My Apps</h1>
              <p className="aps-sub">Full-stack apps generated by Claude AI</p>
            </div>
            <button className="aps-new-btn" onClick={() => navigate('/')}>
              + New App
            </button>
          </div>

          {error && (
            <div className="aps-error">⚠️ {error}</div>
          )}

          {/* Empty state */}
          {!loading && apps.length === 0 && !error && (
            <div className="aps-empty">
              <div className="aps-empty-icon">⚛️</div>
              <h2 className="aps-empty-title">No apps yet</h2>
              <p className="aps-empty-sub">
                Generate your first full-stack app — React frontend, Node.js backend, MySQL schema & setup guide.
              </p>
              <button className="aps-empty-btn" onClick={() => navigate('/')}>
                Build Your First App ⚡
              </button>
            </div>
          )}

          {/* Apps grid */}
          {apps.length > 0 && (
            <div className="aps-grid">
              {apps.map(app => {
                const sc = statusColor(app.status)
                return (
                  <div
                    key={app.id}
                    className="aps-card"
                    onClick={() => app.id && navigate(`/app/${app.id}`)}
                  >
                    {/* Card top */}
                    <div className="aps-card-top">
                      <div className="aps-card-icon">⚛️</div>
                      <div className="aps-card-files">
                        {['App.jsx', 'server.js', 'schema.sql', 'README.md'].map(f => (
                          <div key={f} className="aps-file-chip">{f}</div>
                        ))}
                      </div>
                      {app.status === 'generating' && (
                        <div className="aps-card-spinner" />
                      )}
                    </div>

                    {/* Card body */}
                    <div className="aps-card-body">
                      <div className="aps-card-title-row">
                        <h3 className="aps-card-name">{app.title}</h3>
                        <span
                          className="aps-status-badge"
                          style={{ background: sc.bg, color: sc.color, border: `1px solid ${sc.border}` }}
                        >
                          {statusLabel(app.status)}
                        </span>
                      </div>

                      <p className="aps-card-prompt">"{app.prompt}"</p>

                      <div className="aps-card-footer">
                        <span className="aps-card-date">
                          {new Date(app.created_at).toLocaleDateString('en-IN', {
                            day: 'numeric', month: 'short', year: 'numeric'
                          })}
                        </span>
                        <div className="aps-card-actions">
                          {app.download_paid && (
                            <span className="aps-paid-badge">💳 Paid</span>
                          )}
                          <button
                            className="aps-open-btn"
                            onClick={e => { e.stopPropagation(); app.id && navigate(`/app/${app.id}`) }}
                          >
                            Open →
                          </button>
                          <button
                            className="aps-del-btn"
                            onClick={e => handleDelete(e, app.id)}
                            disabled={deleting === app.id}
                          >
                            {deleting === app.id ? '...' : '🗑️'}
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      </div>
    </>
  )
}

const S = {
  center: {
    minHeight: '60vh', display: 'flex', flexDirection: 'column',
    alignItems: 'center', justifyContent: 'center', gap: 14,
    fontFamily: 'Nunito, sans-serif'
  },
  spinner: {
    width: 36, height: 36,
    border: '3px solid #e2e2ea', borderTopColor: '#5b4fff',
    borderRadius: '50%', animation: 'spin 1s linear infinite'
  }
}

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800;900&family=Nunito:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');
@keyframes spin { to { transform: rotate(360deg) } }
@keyframes fadeUp { from { opacity:0; transform:translateY(12px) } to { opacity:1; transform:translateY(0) } }
@keyframes pulse { 0%,100%{opacity:0.3} 50%{opacity:1} }

.aps-root {
  min-height: 100vh;
  background: #0d0d1a;
  font-family: 'Nunito', sans-serif;
  color: #e0e0f0;
  padding: 40px 24px 80px;
}
.aps-inner { max-width: 960px; margin: 0 auto; }

/* Header */
.aps-header {
  display: flex; align-items: flex-start;
  justify-content: space-between; gap: 16px;
  margin-bottom: 36px; flex-wrap: wrap;
}
.aps-title {
  font-family: 'Playfair Display', serif;
  font-size: 32px; font-weight: 900;
  color: #e0e0f0; margin-bottom: 4px;
}
.aps-sub { font-size: 14px; color: #5050a0; font-weight: 500; }
.aps-new-btn {
  padding: 11px 22px; border-radius: 10px;
  background: #5b4fff; border: none;
  color: #fff; font-size: 14px; font-weight: 800;
  cursor: pointer; font-family: 'Nunito', sans-serif;
  box-shadow: 0 2px 12px rgba(91,79,255,0.35);
  transition: all .18s; white-space: nowrap;
}
.aps-new-btn:hover { opacity: .88; transform: translateY(-1px); }

/* Error */
.aps-error {
  background: rgba(239,68,68,0.08);
  border: 1.5px solid rgba(239,68,68,0.25);
  border-radius: 10px; padding: 12px 16px;
  font-size: 13px; color: #f87171; font-weight: 600;
  margin-bottom: 24px;
}

/* Empty state */
.aps-empty {
  display: flex; flex-direction: column;
  align-items: center; text-align: center;
  padding: 80px 24px; animation: fadeUp .4s ease;
}
.aps-empty-icon { font-size: 56px; margin-bottom: 16px; }
.aps-empty-title {
  font-family: 'Playfair Display', serif;
  font-size: 24px; font-weight: 800;
  color: #e0e0f0; margin-bottom: 10px;
}
.aps-empty-sub {
  font-size: 14px; color: #5050a0; font-weight: 500;
  max-width: 380px; line-height: 1.6; margin-bottom: 24px;
}
.aps-empty-btn {
  padding: 13px 28px; border-radius: 12px;
  background: #5b4fff; border: none;
  color: #fff; font-size: 15px; font-weight: 800;
  cursor: pointer; font-family: 'Nunito', sans-serif;
  box-shadow: 0 4px 18px rgba(91,79,255,0.4);
  transition: all .18s;
}
.aps-empty-btn:hover { opacity: .88; transform: translateY(-2px); }

/* Grid */
.aps-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
}

/* Card */
.aps-card {
  background: #0a0a16;
  border: 1.5px solid #1e1e3a;
  border-radius: 16px; overflow: hidden;
  cursor: pointer; transition: all .22s;
  animation: fadeUp .35s ease both;
  display: flex;
  flex-direction: column;
}
.aps-card:hover {
  border-color: #5b4fff;
  transform: translateY(-4px);
  box-shadow: 0 12px 40px rgba(91,79,255,0.15);
}

/* Card preview area */
.aps-card-top {
  order: 1;
  background: linear-gradient(135deg, #0d0d22, #12122a);
  padding: 20px; height: 110px;
  display: flex; align-items: center;
  justify-content: center; gap: 14px;
  position: relative;
  border-bottom: 1px solid #1e1e3a;
}
.aps-card-icon { font-size: 30px; flex-shrink: 0; }
.aps-card-files {
  display: flex; flex-direction: column; gap: 4px;
}
.aps-file-chip {
  font-family: 'JetBrains Mono', monospace;
  font-size: 10px; font-weight: 500;
  color: #5050a0;
  background: rgba(91,79,255,0.12);
  padding: 2px 8px; border-radius: 4px;
  width: fit-content;
}
.aps-card-spinner {
  position: absolute; top: 10px; right: 10px;
  width: 18px; height: 18px;
  border: 2px solid #1e1e3a;
  border-top-color: #5b4fff;
  border-radius: 50%;
  animation: spin .9s linear infinite;
}

/* Card body */
.aps-card-body {
  order: 2;
  padding: 16px;
}
.aps-card-title-row {
  display: flex; align-items: flex-start;
  justify-content: space-between; gap: 10px;
  margin-bottom: 8px; flex-wrap: wrap;
}
.aps-card-name {
  font-family: 'Playfair Display', serif;
  font-size: 15px; font-weight: 800;
  color: #e0e0f0; line-height: 1.3;
  flex: 1; min-width: 0;
}
.aps-status-badge {
  font-size: 10px; font-weight: 800;
  padding: 3px 9px; border-radius: 100px;
  white-space: nowrap; flex-shrink: 0;
}
.aps-card-prompt {
  font-size: 11px; color: #4040700;
  color: #404070; font-weight: 500;
  line-height: 1.55; margin-bottom: 14px;
  font-style: italic;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.aps-card-footer {
  display: flex; align-items: center;
  justify-content: space-between; gap: 8px;
  flex-wrap: wrap;
}
.aps-card-date {
  font-size: 10px; color: #3a3a5a; font-weight: 600;
}
.aps-card-actions {
  display: flex; align-items: center; gap: 6px;
}
.aps-paid-badge {
  font-size: 10px; font-weight: 800;
  padding: 3px 8px; border-radius: 100px;
  background: rgba(34,197,94,0.1);
  color: #22c55e;
  border: 1px solid rgba(34,197,94,0.25);
}
.aps-open-btn {
  padding: 6px 12px; border-radius: 7px;
  background: #5b4fff; border: none;
  color: #fff; font-size: 11px; font-weight: 800;
  cursor: pointer; font-family: 'Nunito', sans-serif;
  transition: all .15s;
}
.aps-open-btn:hover { opacity: .85; }
.aps-del-btn {
  padding: 6px 9px; border-radius: 7px;
  background: rgba(239,68,68,0.1);
  border: 1px solid rgba(239,68,68,0.2);
  color: #f87171; font-size: 13px;
  cursor: pointer; transition: all .15s;
}
.aps-del-btn:hover { background: rgba(239,68,68,0.2); }
.aps-del-btn:disabled { opacity: .45; cursor: not-allowed; }

@media (max-width: 600px) {
  .aps-grid { grid-template-columns: repeat(2, 1fr); gap: 10px; }
  .aps-title { font-size: 22px; }
  .aps-card-top { height: 90px; padding: 12px; gap: 8px; }
  .aps-card-icon { font-size: 22px; }
  .aps-card-files { gap: 2px; }
  .aps-file-chip { font-size: 8px; padding: 1px 5px; }
  .aps-card-body { padding: 10px; }
  .aps-card-name { font-size: 12px; }
  .aps-card-prompt { font-size: 9px; margin-bottom: 8px; }
  .aps-status-badge { font-size: 8px; padding: 2px 6px; }
  .aps-card-footer { flex-direction: column; align-items: stretch; gap: 6px; }
  .aps-card-actions { justify-content: space-between; }
  .aps-open-btn { flex: 1; text-align: center; font-size: 10px; padding: 5px 8px; }
  .aps-card-date { font-size: 8px; }
}
`